//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhoaHocData.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaiHoc()
        {
            this.BaiTaps = new HashSet<BaiTap>();
        }
    
        public int MaBaiHoc { get; set; }
        public Nullable<int> MaKhoaHoc { get; set; }
        public string TenBaiHoc { get; set; }
        public string VideoLink { get; set; }
        public string MoTa { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<int> MaChuong { get; set; }
        public Nullable<bool> IsHocThu { get; set; }
    
        public virtual Chuong Chuong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaiTap> BaiTaps { get; set; }
    }
}
