//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhoaHocData.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiTap
    {
        public string MaBaiTap { get; set; }
        public string TenBaiTap { get; set; }
        public string FileLink { get; set; }
        public string MaBaiHoc { get; set; }
    
        public virtual BaiHoc BaiHoc { get; set; }
    }
}
