//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhoaHocData.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChamSocKhachHang
    {
        public int MaCSKH { get; set; }
        public Nullable<int> MaLoaiVanDe { get; set; }
        public Nullable<int> MaND { get; set; }
        public string SDTKH { get; set; }
        public string TenKH { get; set; }
        public string TinhTrang { get; set; }
        public string NoiDung { get; set; }
        public string CachXuLy { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
    
        public virtual LoaiVanDe LoaiVanDe { get; set; }
    }
}
