//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhoaHocData.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_GioHang
    {
        public int MaGioHang { get; set; }
        public Nullable<int> MaKhoaHoc { get; set; }
        public Nullable<decimal> DonGia { get; set; }
    
        public virtual KhoaHoc KhoaHoc { get; set; }
        public virtual GioHang GioHang { get; set; }
    }
}
