//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhoaHocData.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGiaKhoaHoc
    {
        public string MaKhoaHoc { get; set; }
        public string MaND { get; set; }
        public Nullable<int> Diem { get; set; }
        public string NoiDung { get; set; }
    
        public virtual KhoaHoc KhoaHoc { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
