//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhoaHocData.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        public string MaDonHang { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public string MaND { get; set; }
        public Nullable<bool> ThanhToan { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public string HinhThucThanhToan { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
