//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhoaHocData.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhuyenMai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhuyenMai()
        {
            this.KhuyenMai_KhachHang = new HashSet<KhuyenMai_KhachHang>();
        }
    
        public int MaKM { get; set; }
        public Nullable<int> MaND { get; set; }
        public string MaApDung { get; set; }
        public string TenKM { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<decimal> GiaTri { get; set; }
        public Nullable<int> ThoiGianKeoDai { get; set; }
        public Nullable<int> Diem { get; set; }
        public Nullable<bool> DangMoBan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhuyenMai_KhachHang> KhuyenMai_KhachHang { get; set; }
    }
}
