//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhoaHocData.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuLuong
    {
        public int MaLuong { get; set; }
        public System.DateTime NgayPhatLuong { get; set; }
        public Nullable<decimal> SoTien { get; set; }
        public Nullable<decimal> TienPhat { get; set; }
        public string GhiChu { get; set; }
    
        public virtual Luong Luong { get; set; }
    }
}
