//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhoaHocData.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Luong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Luong()
        {
            this.LichSuLuongs = new HashSet<LichSuLuong>();
        }
    
        public int MaLuong { get; set; }
        public Nullable<int> MaND { get; set; }
        public Nullable<decimal> Luong1 { get; set; }
        public Nullable<System.DateTime> NgayTinhLuong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuLuong> LichSuLuongs { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
