//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhoaHocData.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiDung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NguoiDung()
        {
            this.DonThuTiens = new HashSet<DonThuTien>();
            this.DonThuTiens1 = new HashSet<DonThuTien>();
        }
    
        public int MaND { get; set; }
        public Nullable<int> MaNhomNguoiDung { get; set; }
        public string TenDN { get; set; }
        public string MatKhau { get; set; }
        public string HoTen { get; set; }
        public string CMND { get; set; }
        public string HinhAnh { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string Diachi { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<bool> DaXoa { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonThuTien> DonThuTiens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonThuTien> DonThuTiens1 { get; set; }
    }
}
