//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhoaHocData.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuenMatKhau
    {
        public int STT { get; set; }
        public string Code { get; set; }
        public string TenDN { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
    }
}
