//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhoaHocData.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quyen
    {
        public int MaQuyen { get; set; }
        public string TenQuyen { get; set; }
        public Nullable<int> MaLoaiQuyen { get; set; }
        public string MetaLink { get; set; }
        public string icon { get; set; }
        public Nullable<bool> HienThi { get; set; }
    }
}
