//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhoaHocData.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoDuTaiKhoan
    {
        public string MaND { get; set; }
        public Nullable<decimal> SoDu { get; set; }
        public Nullable<System.DateTime> NgayNap { get; set; }
        public string NoiDung { get; set; }
        public string MASODU { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
