//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhoaHocData.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrangTri
    {
        public int MaTrangTri { get; set; }
        public string GiaTri { get; set; }
        public Nullable<int> MaLoaiTrangTri { get; set; }
    
        public virtual LoaiTrangTri LoaiTrangTri { get; set; }
    }
}
